version: '3'

services:
  rocketchat:
    image: rocket.chat
    container_name: rocketchat
    ports:
      - 3000:3000
    volumes:
      - rocketchat-data:/app/uploads
      - rocketchat-db:/data/db
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongodb:27017/rocketchat
      - ROOT_URL=http://localhost:3000
      - ROCKETCHAT_USER=admin346
      - ROCKETCHAT_PASSWORD=password
      - ROCKETCHAT_BOT=LeBaguette
    restart: always
    networks:
      - rocketnet

  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - rocketchat-db:/data/db
    restart: always
    networks:
      - rocketnet

  prometheus:
    image: gabdalfa/m169:2.0
    container_name: prometheus
    ports:
      - 9090:9090
    restart: always
    networks:
      - rocketnet

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3030:3030
    environment:
      - GF_SERVER_HTTP_PORT=3030
    restart: always
    networks:
      - rocketnet

volumes:
  rocketchat-data: { driver: local}
  rocketchat-db: { driver: local }

networks:
  rocketnet:
    driver: bridge