# Dieser File legt fest was für Containers betrieben werden. Dadurch weisst Prometheus und schlussendlich auch Grafana wonach es schauen soll.
# Da werden die DNS Einträge verwendet um die Containers zu finden

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rocketchat'
    static_configs:
      - targets: ['rocketchat:3000']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3030']

  - job_name: 'rocketchat-db'
    static_configs:
      - targets: ['mongodb:27017']
